# Generated by Django 5.1.1 on 2024-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[(0, "Administrador"), (1, "Professor"), (2, "Aluno"), (3, "Outros")], default=3
            ),
        ),
    ]
