# Generated by Django 5.0.6 on 2024-07-10 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonRecurrency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, unique=True)),
                ("classroom", models.CharField(blank=True, max_length=10, null=True)),
                ("course", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("attendance_start_datetime", models.DateTimeField()),
                ("attendance_end_datetime", models.DateTimeField()),
                ("is_attendance_registrable", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "lesson_recurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="attendance.lessonrecurrency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonRecurrentDatetime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("datetime", models.DateTimeField()),
                (
                    "lesson_recurrency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_datetimes",
                        to="attendance.lessonrecurrency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("register_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Present"), ("A", "Absent"), ("J", "Justified")], default="A", max_length=1
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="attendance.lesson"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="attendance.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="course_class",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="students", to="attendance.studentclass"
            ),
        ),
        migrations.AddField(
            model_name="lessonrecurrency",
            name="course_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_recurrences",
                to="attendance.studentclass",
            ),
        ),
        migrations.AddField(
            model_name="studentclass",
            name="subjects",
            field=models.ManyToManyField(related_name="student_classes", to="attendance.subject"),
        ),
        migrations.AddField(
            model_name="lessonrecurrency",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="lesson_recurrences", to="attendance.subject"
            ),
        ),
    ]
