# Generated by Django 5.0.6 on 2024-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="passkey",
            field=models.CharField(default="1234567890", max_length=10),
        ),
    ]
