# Generated by Django 5.0.6 on 2024-08-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_lesson_passkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="main_subject",
            field=models.CharField(
                choices=[
                    ("MT", "Matematica"),
                    ("PT", "Portugues"),
                    ("PH", "Fisica"),
                    ("CH", "Quimica"),
                    ("BI", "Biologia"),
                    ("HI", "Historia"),
                    ("GE", "Geografia"),
                    ("PL", "Filosofia"),
                    ("CA", "Atualidades"),
                ],
                default="PT",
                max_length=2,
            ),
        ),
    ]
