# Generated by Django 5.0.7 on 2024-07-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_subject_main_subject"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="is_attendance_registrable",
            new_name="is_manual_attendance_checked",
        ),
        migrations.AddField(
            model_name="lesson",
            name="manual_attendance_last_time_edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
