# Generated by Django 5.0.7 on 2024-07-31 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_rename_is_attendance_registrable_lesson_is_manual_attendance_checked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="students", to="attendance.studentclass"
            ),
        ),
    ]
