# Generated by Django 5.0.6 on 2024-08-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_student_student_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentclass",
            name="modality",
            field=models.CharField(choices=[("ON", "Remoto"), ("IP", "Presencial")], default="IP", max_length=2),
        ),
        migrations.AlterField(
            model_name="studentclass",
            name="course",
            field=models.CharField(choices=[("EX", "Extensivo"), ("SE", "Semi-Extensivo")], default="EX", max_length=2),
        ),
    ]
