# Generated by Django 5.0.6 on 2024-08-11 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_studentclass_modality_alter_studentclass_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentclass",
            name="end_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="studentclass",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
