# Generated by Django 5.0.6 on 2024-10-07 04:05

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_student_student_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonrecurrentdatetime",
            name="datetime",
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_recurrent_datetime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="attendance.lessonrecurrentdatetime",
            ),
        ),
        migrations.AddField(
            model_name="lessonrecurrentdatetime",
            name="day_of_week",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 1, 5, 52, 234432)),
        ),
        migrations.AddField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 1, 5, 52, 234432)),
        ),
    ]
