# Generated by Django 5.0.6 on 2024-10-14 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_student_user_teacher_subject_teacher_user"),
        ("attendance", "0009_remove_lessonrecurrentdatetime_datetime_and_more"),
    ]

    operations = []
