# Generated by Django 5.0.6 on 2024-10-20 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_studentclass_end_datetime_studentclass_modality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="passkey",
            field=models.CharField(default="CURSINHO", max_length=10),
        ),
    ]
