# Generated by Django 5.1.2 on 2024-11-07 15:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_lesson_passkey_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="students",
                to="attendance.studentclass",
            ),
        ),
    ]
