# Generated by Django 5.0.6 on 2024-10-14 14:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_merge_20241014_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentclass",
            name="end_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="studentclass",
            name="modality",
            field=models.CharField(choices=[("ON", "Online"), ("IN", "Presencial")], default="IN", max_length=2),
        ),
        migrations.AddField(
            model_name="studentclass",
            name="start_datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 11, 9, 27, 372957)),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 11, 9, 27, 372957)),
        ),
    ]
