# Generated by Django 5.0.6 on 2024-12-16 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_alter_lessonrecurrentdatetime_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentclass",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="student_classes", to="attendance.subject"
            ),
        ),
    ]
