# Generated by Django 5.0.6 on 2024-10-14 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_studentclass_end_datetime_studentclass_modality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 11, 9, 56, 152254)),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 11, 9, 56, 152254)),
        ),
    ]
