# Generated by Django 5.0.6 on 2024-12-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_alter_lessonrecurrentdatetime_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
