# Generated by Django 5.0.6 on 2024-10-19 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_alter_lessonrecurrentdatetime_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 19, 7, 15, 290364)),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 19, 19, 7, 15, 290364)),
        ),
    ]
