# Generated by Django 5.0.6 on 2024-10-20 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0014_alter_lessonrecurrentdatetime_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="passkey",
            field=models.CharField(default="CURSINHO", max_length=10),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 11, 19, 30, 975036)),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 11, 19, 30, 975036)),
        ),
    ]
