# Generated by Django 5.1.2 on 2024-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0015_alter_lessonrecurrentdatetime_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
