# Generated by Django 5.0.6 on 2024-11-27 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0015_alter_lessonrecurrentdatetime_end_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="end_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 18, 19, 37, 735732)),
        ),
        migrations.AlterField(
            model_name="lessonrecurrentdatetime",
            name="start_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 18, 19, 37, 735732)),
        ),
    ]
